import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, AiFillHtml5 } from 'react-icons/ai';
import { SiLeetcode } from 'react-icons/si';
import { FaReact, FaEllipsisH } from 'react-icons/fa';
import { DiJavascript1, DiJava, DiNodejs, DiLinux } from 'react-icons/di';
import design from "../public/design.png";
import code from "../public/code.png";
import pingsafe from "../public/pingsafe.png";
import pic1 from "../public/pic1.png";
import pic2 from "../public/pic2.png";
import pic3 from "../public/pic3.png";
import pic4 from "../public/pic4.png";
import Image from 'next/image';
//Allows us to customize image
import myimg from '../public/my-img-portfolio.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ritika Pandey Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>

        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>DEVELOPEDbyRITIKA</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer dark:bg-teal-700 dark:rounded-full dark:w-6 dark:h-6 dark:p-2' /></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://drive.google.com/file/d/1gXIGSQyXGOELHHgOc0hyPJbp1wRpvyi0/view?usp=sharing">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Ritika Pandey</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-teal-700'>Developer and Problem Solving Enthusiast</h3>
            <p className='text-md py-2 leading-8 text-gray-800 md:text-xl dark:text-gray-400'>I am a pre-final year student at VIT Bhopal University.I am pursuing BTech in CSE with specialization in Cybersecurity and Digital Forensics.
              I thrive on tackling complex challenges and creating innovative solutions.
              With extensive experience in various programming languages and frameworks.
              Whether working independently or as part of a team, I am dedicated to continuous learning and staying up-to-date with the latest trends and technologies in the field.
              My goal is to leverage my skills and expertise to make a meaningful impact in the world of software development.</p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https://twitter.com/Ritika_P20'><AiFillTwitterCircle /></a>
            <a href='https://www.linkedin.com/in/ritika-pandey-20/'><AiFillLinkedin /></a>
            <a href='https://github.com/Ritika-Pandey01?tab=repositories'><AiFillGithub /></a>
            <a href='https://leetcode.com/ritikapandey0805/'><SiLeetcode /></a>
          </div>
          <div className='mx-auto relative bg-gradient-to-b from-teal-300 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96'>
            <Image src={myimg} fill alt='my-image' className='pl-10 pr-4 py-2' />
          </div>
        </section>
        <section className='py-6'>
          <hr />
          <div className='lg:flex gap-8'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 items-center  bg-teal-50 lg:w-1/2'>
              <div className='flex justify-center'>
                <Image src={code} width={100} height={100} alt='code' />
              </div>

              <h3 className='text-lg font-medium pb-2'>Coding Skills</h3>
              <p className='py-4'>I am proficient in <span className='text-teal-600 font-medium'>Java</span> and I also have knowledge on HTML, CSS, React JS, Node JS, Debugging, Linux, Git/GitHub, and API Testing.
                I create dynamic and visually appealing websites using <span className='text-teal-600 font-medium'>HTML/CSS</span> and <span className='text-teal-600 font-medium'>React JS</span>.
                I use <span className='text-teal-600 font-medium'>Node JS</span> and React JS to create client-side and server-side applications.
                My experience in using <span className='text-teal-600 font-medium'>Linux</span> allows me to work comfortably in a command line environment.

              </p>
              <p className='text-teal-800 font-medium'>Programming Languagues & Other Technologies :</p>
              <p className='text-gray-800 py-4'>Java , HTML, CSS, JavaScript, React JS, Node JS, Linux, Git/GitHub</p>

              <div className='text-4xl flex justify-center gap-2 py-3 text-gray-60 '>
                <DiJava />
                <AiFillHtml5 />
                <DiJavascript1 />
                <FaReact />
                <DiNodejs />
                <DiLinux />
                <AiFillGithub />
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 items-center  bg-teal-50 py-10 lg:w-1/2'>
              <div className='flex justify-center'>
                <Image src={design} width={100} height={100} alt='code' />
              </div>

              <h3 className='text-lg font-medium pb-2'>Certifications</h3>
              <p className='py-4'>I have successfully completed the <span className='text-teal-600 font-medium'>Google UX Design Professional Certificate</span> from Coursera. This course provided me with a comprehensive understanding of the principles and practices of user experience design.
                This helped me to create <span className='text-teal-600 font-medium'>user-centric designs</span> that are intuitive, accessible, and aesthetically pleasing.
                After  completing this certification, I was successfully able to conduct user research and implement  <span className='text-teal-600 font-medium'>user persona design</span> in my personal project.

              </p>
              <p className='text-teal-800 font-medium'>Platform : <span className='text-gray-800 py-4'>Coursera</span></p>

            </div>
          </div>
          <hr className='py-4' />
          <div >
            <h2 className='font-medium text-3xl text-center dark:text-gray-300'>Experience</h2>
            <div className='lg:flex gap-8'>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 items-center  bg-blue-50 lg:w-1/2'>
                <div className='flex justify-center'>
                  <Image src={pingsafe} width={100} height={100} alt='code' />
                </div>

                <h3 className='text-lg font-medium pb-2'>Software Engineering Intern</h3>
                <p className='text-teal-800 font-medium'>Duration: <span className='text-gray-600'>Aug 22 - Dec 22</span></p>
                <p className='py-4'>
                  Researched the <span className='text-teal-600 font-medium'>SaaS misconfigurations</span> for platforms like <span className='text-teal-600 font-medium'>Snowflake</span> and <span className='text-teal-600 font-medium'>Microsoft 365</span>.
                  Wrote clear and clean code for the misconfigurations like FIDO2 authentication unattested, password expiration disabled, app disabled, network policy not set and various others using Node JS for 2 SaaS platforms by using <span className='text-teal-600 font-medium'>Microsoft Graph API</span> and <span className='text-teal-600 font-medium'>Snowflake SQL REST API</span>.
                  Developed the compliance reports for client using HTML, Tailwind and Puppeteer.
                </p>
                <p className='text-teal-800 font-medium'>Company : <span className='text-gray-800 py-4'>PingSafe</span></p>

              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 items-center  bg-blue-50 lg:w-1/2'>
                <div className='flex justify-center'>
                  <Image src={pingsafe} width={100} height={100} alt='code' />
                </div>

                <h3 className='text-lg font-medium pb-2'>Cloud Security Solutions Intern</h3>
                <p className='text-teal-800 font-medium'>Duration: <span className='text-gray-600'>Sep 21 - Feb 22</span></p>
                <p className='py-4'>
                  Researched various security misconfigurations in the <span className='text-teal-600 font-medium'>AWS</span> and <span className='text-teal-600 font-medium'>Azure cloud</span>.
                  Identified and removed various cloud misconfigurations present on the AWS and Azure cloud.
                  Documented technical workflows involved in removing the misconfigurations present in AWS and Azure cloud for  <span className='text-teal-600 font-medium'>PingSafe's Knowledge Base</span>.
                  Identified misconfigurations like Users MFA Disabled, Groups Without Users, S3 Bucket Insecure Read Access
                  S3 Buckets With Global Policy and soon for AWS Services, like AWS IAM,Amazon S3 etc.

                </p>
                <p className='text-teal-800 font-medium'>Company : <span className='text-gray-800 py-4'>PingSafe</span></p>

              </div>
            </div>
          </div>
          <hr />
          <div>
            <h2 className='font-medium text-3xl text-center pt-4 pb-2 dark:text-gray-300 '>Projects</h2>
            <div className='flex flex-col  gap-10 pb-10 lg:flex-row lg:flex-wrap'>
              <div className='basis-1/3 flex-1'>
                <p className='text-gray-900 font-medium text-center dark:text-gray-200 pt-4'>BooksEra</p>
                <a href='https://github.com/Ritika-Pandey01/BooksEra'><Image src={pic1}
                  alt='BooksEra'
                  className='rounded-lg object-cover'
                  style={{ width: '100%', height: '100%' }}
                /></a>

              </div>
              <div className='basis-1/3 flex-1'>
                <p className='text-gray-900 font-medium text-center dark:text-gray-200 pt-4'>Auth App</p>
                <a href='https://github.com/Ritika-Pandey01/AuthApp'><Image src={pic2}
                  alt='Secrets App'
                  className='rounded-lg object-cover'
                  style={{ width: '100%', height: '100%' }}

                /></a>

              </div>
              <div className='basis-1/3 flex-1'>
                <p className='text-gray-900 font-medium text-center dark:text-gray-200 pt-4'>Drum Beats</p>
                <a href='https://github.com/Ritika-Pandey01/Drum-Beats'><Image src={pic3}
                  alt='Drum Beats'
                  className='rounded-lg object-cover'
                  style={{ width: '100%', height: '100%' }}
                /></a>

              </div>
              <div className='basis-1/3 flex-1'>
                <p className='text-gray-900 font-medium text-center dark:text-gray-200 pt-4'>Simon Game</p>
                <a href='https://github.com/Ritika-Pandey01/Simon-Game'><Image src={pic4}
                  alt='Simon Game'
                  className='rounded-lg object-cover'
                  style={{ width: '100%', height: '100%' }}
                /></a>

              </div>
            </div>

          </div>
        </section>
      </main>
    </div >
  )
}