import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, AiFillHtml5 } from 'react-icons/ai';
import { SiLeetcode } from 'react-icons/si';
import { FaReact } from 'react-icons/fa';
import { DiJavascript1, DiJava, DiNodejs, DiLinux } from 'react-icons/di';
import design from "../public/design.png";
import code from "../public/code.png";
import pingsafe from "../public/pingsafe.png";
import pic1 from "../public/pic1.png";
import pic2 from "../public/pic2.png";
import pic3 from "../public/pic3.png";
import pic4 from "../public/pic4.png";
import Image from 'next/image';
//Allows us to customize image
import myimg from '../public/my-img-portfolio.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ritika Pandey Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40'>

        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>DEVELOPEDbyRP</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer' /></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://drive.google.com/file/d/1gXIGSQyXGOELHHgOc0hyPJbp1wRpvyi0/view?usp=sharing">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Ritika Pandey</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Developer and Problem Solving Enthusiast</h3>
            <p className='text-md py-2 leading-8 text-gray-800 md:text-xl'>I am a pre-final year student at VIT Bhopal University.I am pursuing BTech in CSE with specialization in Cybersecurity and Digital Forensics.
              I thrive on tackling complex challenges and creating innovative solutions.
              With extensive experience in various programming languages and frameworks.
              Whether working independently or as part of a team, I am dedicated to continuous learning and staying up-to-date with the latest trends and technologies in the field.
              My goal is to leverage my skills and expertise to make a meaningful impact in the world of software development.</p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https://twitter.com/Ritika_P20'><AiFillTwitterCircle /></a>
            <a href='https://www.linkedin.com/in/ritika-pandey-20/'><AiFillLinkedin /></a>
            <a href='https://github.com/Ritika-Pandey01?tab=repositories'><AiFillGithub /></a>
            <a href='https://leetcode.com/ritikapandey0805/'><SiLeetcode /></a>
          </div>
          <div className='mx-auto relative bg-gradient-to-b from-teal-300 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96'>
            <Image src={myimg} fill alt='my-image' className='pl-10 pr-4 py-2' />
          </div>
        </section>
        <section>


          <div className='lg:flex gap-8'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 items-center  bg-teal-50 lg:w-1/2'>
              <div className='flex justify-center'>
                <Image src={code} width={100} height={100} alt='code' />
              </div>

              <h3 className='text-lg font-medium pb-2'>Coding Skills</h3>
              <p className='py-4'>I am proficient in <span className='text-teal-600 font-medium'>Java</span> and I also have knowledge on HTML, CSS, React JS, Node JS, Debugging, Linux, Git/GitHub, and API Testing.
                I create dynamic and visually appealing websites using <span className='text-teal-600 font-medium'>HTML/CSS</span> and <span className='text-teal-600 font-medium'>React JS</span>.
                I use <span className='text-teal-600 font-medium'>Node JS</span> and React JS to create client-side and server-side applications.
                My experience in using <span className='text-teal-600 font-medium'>Linux</span> allows me to work comfortably in a command line environment.

              </p>
              <p className='text-teal-800 font-medium'>Programming Languagues & Other Technologies :</p>
              <p className='text-gray-800 py-4'>Java , HTML, CSS, JavaScript, React JS, Node JS, Linux, Git/GitHub</p>

              <div className='text-4xl flex justify-center gap-2 py-3 text-gray-60 '>
                <DiJava />
                <AiFillHtml5 />
                <DiJavascript1 />
                <FaReact />
                <DiNodejs />
                <DiLinux />
                <AiFillGithub />
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 items-center  bg-teal-50 py-10 lg:w-1/2'>
              <div className='flex justify-center'>
                <Image src={design} width={100} height={100} alt='code' />
              </div>

              <h3 className='text-lg font-medium pb-2'>Certifications</h3>
              <p className='py-4'>I have successfully completed the <span className='text-teal-600 font-medium'>Google UX Design Professional Certificate</span> from Coursera. This course provided me with a comprehensive understanding of the principles and practices of user experience design.
                This helped me to create <span className='text-teal-600 font-medium'>user-centric designs</span> that are intuitive, accessible, and aesthetically pleasing.
                After  completing this certification, I was successfully able to conduct user research and implement  <span className='text-teal-600 font-medium'>user persona design</span> in my personal project.

              </p>
              <p className='text-teal-800 font-medium'>Platform : <span className='text-gray-800 py-4'>Coursera</span></p>

            </div>
          </div>
          <div >
            <h2 className='font-medium text-3xl text-center'>Experience</h2>
            <div className='lg:flex gap-8'>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 items-center  bg-blue-50'>
                <div className='flex justify-center'>
                  <Image src={pingsafe} width={100} height={100} alt='code' />
                </div>

                <h3 className='text-lg font-medium pb-2'>Software Engineering Intern</h3>
                <p className='text-teal-800 font-medium'>Duration: <span className='text-gray-600'>Aug 22 - Dec 22</span></p>
                <p className='py-4'>I have successfully completed the <span className='text-teal-600 font-medium'>Google UX Design Professional Certificate</span> from Coursera. This course provided me with a comprehensive understanding of the principles and practices of user experience design.
                  This helped me to create <span className='text-teal-600 font-medium'>user-centric designs</span> that are intuitive, accessible, and aesthetically pleasing.
                  After  completing this certification, I was successfully able to conduct user research and implement  <span className='text-teal-600 font-medium'>user persona design</span> in my personal project.

                </p>
                <p className='text-teal-800 font-medium'>Company : <span className='text-gray-800 py-4'>PingSafe</span></p>

              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 items-center  bg-blue-50'>
                <div className='flex justify-center'>
                  <Image src={pingsafe} width={100} height={100} alt='code' />
                </div>

                <h3 className='text-lg font-medium pb-2'>Cloud Security Solutions Intern</h3>
                <p className='text-teal-800 font-medium'>Duration: <span className='text-gray-600'>Sep 21 - Feb 22</span></p>
                <p className='py-4'>I have successfully completed the <span className='text-teal-600 font-medium'>Google UX Design Professional Certificate</span> from Coursera. This course provided me with a comprehensive understanding of the principles and practices of user experience design.
                  This helped me to create <span className='text-teal-600 font-medium'>user-centric designs</span> that are intuitive, accessible, and aesthetically pleasing.
                  After  completing this certification, I was successfully able to conduct user research and implement  <span className='text-teal-600 font-medium'>user persona design</span> in my personal project.

                </p>
                <p className='text-teal-800 font-medium'>Company : <span className='text-gray-800 py-4'>PingSafe</span></p>

              </div>
            </div>
          </div>
          <div>
            <h2 className='font-medium text-3xl text-center py-4'>Projects</h2>
            <div className='flex flex-col  gap-10 py-10 lg:flex-row lg:flex-wrap'>
              <div>
                <Image src={pic1} alt='BooksEra' />
              </div>
              <div>
                <Image src={pic2} alt='Secrets App' />
              </div>
              <div>
                <Image src={pic3} alt='Drum Beats' />
              </div>
              <div>
                <Image src={pic4} alt='Simon Game' />
              </div>
            </div>

          </div>
        </section>
      </main>
    </div >
  )
}
